### ISSUE TITLE
weak code ngl didnt even import cv2 👎👎🥱🥱

### ISSUE THREAD

**Issue by syntheticlol** [alluding/discord-webhook-protector#1]

**Comment by alluding** [comment]
```plaintext
You are at start location [0, 0] in mountain area of NxN and you can only move in one of the four cardinal directions (i.e. North, East, South, West). Return minimal number of climb rounds to target location [N-1, N-1]. Number of climb rounds between adjacent locations is defined as difference of location altitudes (ascending or descending).

Location altitude is defined as an integer number (0-9).
```

lmk when solved skid 🤓

**Comment by syntheticlol** [comment]
solved 
import heapq

def path_finder(area):
    area = area.splitlines()
    n = len(area)

    def get_neighbors(x, y):
        neighbors = []
        directions = [(0, 1), (0, -1), (1, 0), (-1, 0)]
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < n and 0 <= ny < n:
                neighbors.append((nx, ny))
        return neighbors

    graph = {i * n + j: {} for i in range(n) for j in range(n)}
    for i in range(n):
        for j in range(n):
            for ni, nj in get_neighbors(i, j):
                weight = abs(int(area[i][j]) - int(area[ni][nj]))
                graph[i * n + j][ni * n + nj] = weight

    start, target = 0, n * n - 1
    distances = {node: float('inf') for node in graph}
    distances[start] = 0
    heap = [(0, start)]

    while heap:
        dist, node = heapq.heappop(heap)
        if node == target:
            return dist
        for neighbor, weight in graph[node].items():
            new_dist = dist + weight
            if new_dist < distances[neighbor]:
                distances[neighbor] = new_dist
                heapq.heappush(heap, (new_dist, neighbor))

    return -1

**Comment by alluding** [comment]
> solved import heapq
> 
> def path_finder(area): area = area.splitlines() n = len(area)
> 
> ```
> def get_neighbors(x, y):
>     neighbors = []
>     directions = [(0, 1), (0, -1), (1, 0), (-1, 0)]
>     for dx, dy in directions:
>         nx, ny = x + dx, y + dy
>         if 0 <= nx < n and 0 <= ny < n:
>             neighbors.append((nx, ny))
>     return neighbors
> 
> graph = {i * n + j: {} for i in range(n) for j in range(n)}
> for i in range(n):
>     for j in range(n):
>         for ni, nj in get_neighbors(i, j):
>             weight = abs(int(area[i][j]) - int(area[ni][nj]))
>             graph[i * n + j][ni * n + nj] = weight
> 
> start, target = 0, n * n - 1
> distances = {node: float('inf') for node in graph}
> distances[start] = 0
> heap = [(0, start)]
> 
> while heap:
>     dist, node = heapq.heappop(heap)
>     if node == target:
>         return dist
>     for neighbor, weight in graph[node].items():
>         new_dist = dist + weight
>         if new_dist < distances[neighbor]:
>             distances[neighbor] = new_dist
>             heapq.heappush(heap, (new_dist, neighbor))
> 
> return -1
> ```

![image](https://github.com/alluding/discord-webhook-protector/assets/149972831/8f221cc8-6897-41da-8be4-e15c393d6963)

I solved it for you skid

**Comment by syntheticlol** [comment]
photoshop + personal problem ngl + u suck couldnt even solve a 1kyu
